// server/createIceTables.js
// One-time migration: creates 3 ICE COT tables with identical schema to CFTC tables.
// Run once: node server/createIceTables.js

import dotenv from 'dotenv';
dotenv.config({ path: './server/.env' });

import pool from './db.js';

const CREATE_TABLE_SQL = (tableName) => `
CREATE TABLE IF NOT EXISTS ${tableName} (
    report_date_as_mm_dd_yyyy       DATE NOT NULL,
    market_and_exchange_names       TEXT,
    as_of_date_in_form_yymmdd       TEXT,
    cftc_contract_market_code       TEXT,
    cftc_market_code                TEXT,
    cftc_region_code                TEXT,
    cftc_commodity_code             TEXT,
    open_interest_all               BIGINT,
    prod_merc_positions_long_all    BIGINT,
    prod_merc_positions_short_all   BIGINT,
    swap_positions_long_all         BIGINT,
    swap_positions_short_all        BIGINT,
    swap_positions_spread_all       BIGINT,
    m_money_positions_long_all      BIGINT,
    m_money_positions_short_all     BIGINT,
    m_money_positions_spread_all    BIGINT,
    other_rept_positions_long_all   BIGINT,
    other_rept_positions_short_all  BIGINT,
    other_rept_positions_spread_all BIGINT,
    tot_rept_positions_long_all     BIGINT,
    tot_rept_positions_short_all    BIGINT,
    nonrept_positions_long_all      BIGINT,
    nonrept_positions_short_all     BIGINT,
    open_interest_old               BIGINT,
    prod_merc_positions_long_old    BIGINT,
    prod_merc_positions_short_old   BIGINT,
    swap_positions_long_old         BIGINT,
    swap_positions_short_old        BIGINT,
    swap_positions_spread_old       BIGINT,
    m_money_positions_long_old      BIGINT,
    m_money_positions_short_old     BIGINT,
    m_money_positions_spread_old    BIGINT,
    other_rept_positions_long_old   BIGINT,
    other_rept_positions_short_old  BIGINT,
    other_rept_positions_spread_old BIGINT,
    tot_rept_positions_long_old     BIGINT,
    tot_rept_positions_short_old    BIGINT,
    nonrept_positions_long_old      BIGINT,
    nonrept_positions_short_old     BIGINT,
    open_interest_other             BIGINT,
    prod_merc_positions_long_other  BIGINT,
    prod_merc_positions_short_other BIGINT,
    swap_positions_long_other       BIGINT,
    swap_positions_short_other      BIGINT,
    swap_positions_spread_other     BIGINT,
    m_money_positions_long_other    BIGINT,
    m_money_positions_short_other   BIGINT,
    m_money_positions_spread_other  BIGINT,
    other_rept_positions_long_other BIGINT,
    other_rept_positions_short_other BIGINT,
    other_rept_positions_spread_othr BIGINT,
    tot_rept_positions_long_other   BIGINT,
    tot_rept_positions_short_other  BIGINT,
    nonrept_positions_long_other    BIGINT,
    nonrept_positions_short_other   BIGINT,
    change_in_open_interest_all     BIGINT,
    change_in_prod_merc_long_all    BIGINT,
    change_in_prod_merc_short_all   BIGINT,
    change_in_swap_long_all         BIGINT,
    change_in_swap_short_all        BIGINT,
    change_in_swap_spread_all       BIGINT,
    change_in_m_money_long_all      BIGINT,
    change_in_m_money_short_all     BIGINT,
    change_in_m_money_spread_all    BIGINT,
    change_in_other_rept_long_all   BIGINT,
    change_in_other_rept_short_all  BIGINT,
    change_in_other_rept_spread_all BIGINT,
    change_in_tot_rept_long_all     BIGINT,
    change_in_tot_rept_short_all    BIGINT,
    change_in_nonrept_long_all      BIGINT,
    change_in_nonrept_short_all     BIGINT,
    pct_of_open_interest_all        DECIMAL(10,2),
    pct_of_oi_prod_merc_long_all    DECIMAL(10,2),
    pct_of_oi_prod_merc_short_all   DECIMAL(10,2),
    pct_of_oi_swap_long_all         DECIMAL(10,2),
    pct_of_oi_swap_short_all        DECIMAL(10,2),
    pct_of_oi_swap_spread_all       DECIMAL(10,2),
    pct_of_oi_m_money_long_all      DECIMAL(10,2),
    pct_of_oi_m_money_short_all     DECIMAL(10,2),
    pct_of_oi_m_money_spread_all    DECIMAL(10,2),
    pct_of_oi_other_rept_long_all   DECIMAL(10,2),
    pct_of_oi_other_rept_short_all  DECIMAL(10,2),
    pct_of_oi_other_rept_spread_all DECIMAL(10,2),
    pct_of_oi_tot_rept_long_all     DECIMAL(10,2),
    pct_of_oi_tot_rept_short_all    DECIMAL(10,2),
    pct_of_oi_nonrept_long_all      DECIMAL(10,2),
    pct_of_oi_nonrept_short_all     DECIMAL(10,2),
    pct_of_open_interest_old        DECIMAL(10,2),
    pct_of_oi_prod_merc_long_old    DECIMAL(10,2),
    pct_of_oi_prod_merc_short_old   DECIMAL(10,2),
    pct_of_oi_swap_long_old         DECIMAL(10,2),
    pct_of_oi_swap_short_old        DECIMAL(10,2),
    pct_of_oi_swap_spread_old       DECIMAL(10,2),
    pct_of_oi_m_money_long_old      DECIMAL(10,2),
    pct_of_oi_m_money_short_old     DECIMAL(10,2),
    pct_of_oi_m_money_spread_old    DECIMAL(10,2),
    pct_of_oi_other_rept_long_old   DECIMAL(10,2),
    pct_of_oi_other_rept_short_old  DECIMAL(10,2),
    pct_of_oi_other_rept_spread_old DECIMAL(10,2),
    pct_of_oi_tot_rept_long_old     DECIMAL(10,2),
    pct_of_oi_tot_rept_short_old    DECIMAL(10,2),
    pct_of_oi_nonrept_long_old      DECIMAL(10,2),
    pct_of_oi_nonrept_short_old     DECIMAL(10,2),
    pct_of_open_interest_other      DECIMAL(10,2),
    pct_of_oi_prod_merc_long_other  DECIMAL(10,2),
    pct_of_oi_prod_merc_short_other DECIMAL(10,2),
    pct_of_oi_swap_long_other       DECIMAL(10,2),
    pct_of_oi_swap_short_other      DECIMAL(10,2),
    pct_of_oi_swap_spread_other     DECIMAL(10,2),
    pct_of_oi_m_money_long_other    DECIMAL(10,2),
    pct_of_oi_m_money_short_other   DECIMAL(10,2),
    pct_of_oi_m_money_spread_other  DECIMAL(10,2),
    pct_of_oi_other_rept_long_other DECIMAL(10,2),
    pct_of_oi_other_rept_short_other DECIMAL(10,2),
    pct_of_oi_other_rept_spread_othr DECIMAL(10,2),
    pct_of_oi_tot_rept_long_other   DECIMAL(10,2),
    pct_of_oi_tot_rept_short_other  DECIMAL(10,2),
    pct_of_oi_nonrept_long_other    DECIMAL(10,2),
    pct_of_oi_nonrept_short_other   DECIMAL(10,2),
    traders_tot_all                 INTEGER,
    traders_prod_merc_long_all      INTEGER,
    traders_prod_merc_short_all     INTEGER,
    traders_swap_long_all           INTEGER,
    traders_swap_short_all          INTEGER,
    traders_swap_spread_all         INTEGER,
    traders_m_money_long_all        INTEGER,
    traders_m_money_short_all       INTEGER,
    traders_m_money_spread_all      INTEGER,
    traders_other_rept_long_all     INTEGER,
    traders_other_rept_short_all    INTEGER,
    traders_other_rept_spread_all   INTEGER,
    traders_tot_rept_long_all       INTEGER,
    traders_tot_rept_short_all      INTEGER,
    traders_tot_old                 INTEGER,
    traders_prod_merc_long_old      INTEGER,
    traders_prod_merc_short_old     INTEGER,
    traders_swap_long_old           INTEGER,
    traders_swap_short_old          INTEGER,
    traders_swap_spread_old         INTEGER,
    traders_m_money_long_old        INTEGER,
    traders_m_money_short_old       INTEGER,
    traders_m_money_spread_old      INTEGER,
    traders_other_rept_long_old     INTEGER,
    traders_other_rept_short_old    INTEGER,
    traders_other_rept_spread_old   INTEGER,
    traders_tot_rept_long_old       INTEGER,
    traders_tot_rept_short_old      INTEGER,
    traders_tot_other               INTEGER,
    traders_prod_merc_long_other    INTEGER,
    traders_prod_merc_short_other   INTEGER,
    traders_swap_long_other         INTEGER,
    traders_swap_short_other        INTEGER,
    traders_swap_spread_other       INTEGER,
    traders_m_money_long_other      INTEGER,
    traders_m_money_short_other     INTEGER,
    traders_m_money_spread_other    INTEGER,
    traders_other_rept_long_other   INTEGER,
    traders_other_rept_short_other  INTEGER,
    traders_other_rept_spread_other INTEGER,
    traders_tot_rept_long_other     INTEGER,
    traders_tot_rept_short_other    INTEGER,
    conc_gross_le_4_tdr_long_all    DECIMAL(10,2),
    conc_gross_le_4_tdr_short_all   DECIMAL(10,2),
    conc_gross_le_8_tdr_long_all    DECIMAL(10,2),
    conc_gross_le_8_tdr_short_all   DECIMAL(10,2),
    conc_net_le_4_tdr_long_all      DECIMAL(10,2),
    conc_net_le_4_tdr_short_all     DECIMAL(10,2),
    conc_net_le_8_tdr_long_all      DECIMAL(10,2),
    conc_net_le_8_tdr_short_all     DECIMAL(10,2),
    conc_gross_le_4_tdr_long_old    DECIMAL(10,2),
    conc_gross_le_4_tdr_short_old   DECIMAL(10,2),
    conc_gross_le_8_tdr_long_old    DECIMAL(10,2),
    conc_gross_le_8_tdr_short_old   DECIMAL(10,2),
    conc_net_le_4_tdr_long_old      DECIMAL(10,2),
    conc_net_le_4_tdr_short_old     DECIMAL(10,2),
    conc_net_le_8_tdr_long_old      DECIMAL(10,2),
    conc_net_le_8_tdr_short_old     DECIMAL(10,2),
    conc_gross_le_4_tdr_long_other  DECIMAL(10,2),
    conc_gross_le_4_tdr_short_other DECIMAL(10,2),
    conc_gross_le_8_tdr_long_other  DECIMAL(10,2),
    conc_gross_le_8_tdr_short_other DECIMAL(10,2),
    conc_net_le_4_tdr_long_other    DECIMAL(10,2),
    conc_net_le_4_tdr_short_other   DECIMAL(10,2),
    conc_net_le_8_tdr_long_other    DECIMAL(10,2),
    conc_net_le_8_tdr_short_other   DECIMAL(10,2),
    contract_units                  TEXT,
    futonly_or_combined             TEXT,
    PRIMARY KEY (report_date_as_mm_dd_yyyy)
);
`;

async function createTables() {
    const tables = ['ice_london_cocoa', 'ice_white_sugar', 'ice_robusta_coffee'];
    const client = await pool.connect();
    try {
        for (const table of tables) {
            console.log(`Creating table: ${table}...`);
            await client.query(CREATE_TABLE_SQL(table));
            console.log(`✔ ${table} created (or already exists).`);
        }
        console.log('\n✅ All ICE tables ready.');
    } catch (err) {
        console.error('Error creating tables:', err.message);
        process.exit(1);
    } finally {
        client.release();
        await pool.end();
    }
}

createTables();
