// Complete column mapping from CSV to database
const COMPLETE_COLUMN_MAPPING = {
    // Basic info
    'Report_Date_as_MM_DD_YYYY': 'report_date_as_mm_dd_yyyy',
    'CFTC_Contract_Market_Code': 'cftc_contract_market_code',
    'CFTC_Market_Code': 'cftc_market_code',
    'CFTC_Region_Code': 'cftc_region_code',
    'CFTC_Commodity_Code': 'cftc_commodity_code',

    // All positions
    'Open_Interest_All': 'open_interest_all',
    'Prod_Merc_Positions_Long_ALL': 'prod_merc_positions_long_all',
    'Prod_Merc_Positions_Short_ALL': 'prod_merc_positions_short_all',
    'Swap_Positions_Long_All': 'swap_positions_long_all',
    'Swap__Positions_Short_All': 'swap_positions_short_all',
    'Swap__Positions_Spread_All': 'swap_positions_spread_all',
    'M_Money_Positions_Long_ALL': 'm_money_positions_long_all',
    'M_Money_Positions_Short_ALL': 'm_money_positions_short_all',
    'M_Money_Positions_Spread_ALL': 'm_money_positions_spread_all',
    'Other_Rept_Positions_Long_ALL': 'other_rept_positions_long_all',
    'Other_Rept_Positions_Short_ALL': 'other_rept_positions_short_all',
    'Other_Rept_Positions_Spread_ALL': 'other_rept_positions_spread_all',
    'Tot_Rept_Positions_Long_All': 'tot_rept_positions_long_all',
    'Tot_Rept_Positions_Short_All': 'tot_rept_positions_short_all',
    'NonRept_Positions_Long_All': 'nonrept_positions_long_all',
    'NonRept_Positions_Short_All': 'nonrept_positions_short_all',

    // Old positions
    'Open_Interest_Old': 'open_interest_old',
    'Prod_Merc_Positions_Long_Old': 'prod_merc_positions_long_old',
    'Prod_Merc_Positions_Short_Old': 'prod_merc_positions_short_old',
    'Swap_Positions_Long_Old': 'swap_positions_long_old',
    'Swap_Positions_Short_Old': 'swap_positions_short_old',
    'Swap_Positions_Spread_Old': 'swap_positions_spread_old',
    'M_Money_Positions_Long_Old': 'm_money_positions_long_old',
    'M_Money_Positions_Short_Old': 'm_money_positions_short_old',
    'M_Money_Positions_Spread_Old': 'm_money_positions_spread_old',
    'Other_Rept_Positions_Long_Old': 'other_rept_positions_long_old',
    'Other_Rept_Positions_Short_Old': 'other_rept_positions_short_old',
    'Other_Rept_Positions_Spread_Old': 'other_rept_positions_spread_old',
    'Tot_Rept_Positions_Long_Old': 'tot_rept_positions_long_old',
    'Tot_Rept_Positions_Short_Old': 'tot_rept_positions_short_old',
    'NonRept_Positions_Long_Old': 'nonrept_positions_long_old',
    'NonRept_Positions_Short_Old': 'nonrept_positions_short_old',

    // Other positions
    'Open_Interest_Other': 'open_interest_other',
    'Prod_Merc_Positions_Long_Other': 'prod_merc_positions_long_other',
    'Prod_Merc_Positions_Short_Other': 'prod_merc_positions_short_other',
    'Swap_Positions_Long_Other': 'swap_positions_long_other',
    'Swap_Positions_Short_Other': 'swap_positions_short_other',
    'Swap_Positions_Spread_Other': 'swap_positions_spread_other',
    'M_Money_Positions_Long_Other': 'm_money_positions_long_other',
    'M_Money_Positions_Short_Other': 'm_money_positions_short_other',
    'M_Money_Positions_Spread_Other': 'm_money_positions_spread_other',
    'Other_Rept_Positions_Long_Other': 'other_rept_positions_long_other',
    'Other_Rept_Positions_Short_Other': 'other_rept_positions_short_other',
    'Other_Rept_Positions_Spread_Othr': 'other_rept_positions_spread_othr',
    'Tot_Rept_Positions_Long_Other': 'tot_rept_positions_long_other',
    'Tot_Rept_Positions_Short_Other': 'tot_rept_positions_short_other',
    'NonRept_Positions_Long_Other': 'nonrept_positions_long_other',
    'NonRept_Positions_Short_Other': 'nonrept_positions_short_other',

    // Changes
    'Change_in_Open_Interest_All': 'change_in_open_interest_all',
    'Change_in_Prod_Merc_Long_All': 'change_in_prod_merc_long_all',
    'Change_in_Prod_Merc_Short_All': 'change_in_prod_merc_short_all',
    'Change_in_Swap_Long_All': 'change_in_swap_long_all',
    'Change_in_Swap_Short_All': 'change_in_swap_short_all',
    'Change_in_Swap_Spread_All': 'change_in_swap_spread_all',
    'Change_in_M_Money_Long_All': 'change_in_m_money_long_all',
    'Change_in_M_Money_Short_All': 'change_in_m_money_short_all',
    'Change_in_M_Money_Spread_All': 'change_in_m_money_spread_all',
    'Change_in_Other_Rept_Long_All': 'change_in_other_rept_long_all',
    'Change_in_Other_Rept_Short_All': 'change_in_other_rept_short_all',
    'Change_in_Other_Rept_Spread_All': 'change_in_other_rept_spread_all',
    'Change_in_Tot_Rept_Long_All': 'change_in_tot_rept_long_all',
    'Change_in_Tot_Rept_Short_All': 'change_in_tot_rept_short_all',
    'Change_in_NonRept_Long_All': 'change_in_nonrept_long_all',
    'Change_in_NonRept_Short_All': 'change_in_nonrept_short_all',

    // Percentages - All
    'Pct_of_Open_Interest_All': 'pct_of_open_interest_all',
    'Pct_of_OI_Prod_Merc_Long_All': 'pct_of_oi_prod_merc_long_all',
    'Pct_of_OI_Prod_Merc_Short_All': 'pct_of_oi_prod_merc_short_all',
    'Pct_of_OI_Swap_Long_All': 'pct_of_oi_swap_long_all',
    'Pct_of_OI_Swap_Short_All': 'pct_of_oi_swap_short_all',
    'Pct_of_OI_Swap_Spread_All': 'pct_of_oi_swap_spread_all',
    'Pct_of_OI_M_Money_Long_All': 'pct_of_oi_m_money_long_all',
    'Pct_of_OI_M_Money_Short_All': 'pct_of_oi_m_money_short_all',
    'Pct_of_OI_M_Money_Spread_All': 'pct_of_oi_m_money_spread_all',
    'Pct_of_OI_Other_Rept_Long_All': 'pct_of_oi_other_rept_long_all',
    'Pct_of_OI_Other_Rept_Short_All': 'pct_of_oi_other_rept_short_all',
    'Pct_of_OI_Other_Rept_Spread_All': 'pct_of_oi_other_rept_spread_all',
    'Pct_of_OI_Tot_Rept_Long_All': 'pct_of_oi_tot_rept_long_all',
    'Pct_of_OI_Tot_Rept_Short_All': 'pct_of_oi_tot_rept_short_all',
    'Pct_of_OI_NonRept_Long_All': 'pct_of_oi_nonrept_long_all',
    'Pct_of_OI_NonRept_Short_All': 'pct_of_oi_nonrept_short_all',

    // Percentages - Old
    'Pct_of_Open_Interest_Old': 'pct_of_open_interest_old',
    'Pct_of_OI_Prod_Merc_Long_Old': 'pct_of_oi_prod_merc_long_old',
    'Pct_of_OI_Prod_Merc_Short_Old': 'pct_of_oi_prod_merc_short_old',
    'Pct_of_OI_Swap_Long_Old': 'pct_of_oi_swap_long_old',
    'Pct_of_OI_Swap_Short_Old': 'pct_of_oi_swap_short_old',
    'Pct_of_OI_Swap_Spread_Old': 'pct_of_oi_swap_spread_old',
    'Pct_of_OI_M_Money_Long_Old': 'pct_of_oi_m_money_long_old',
    'Pct_of_OI_M_Money_Short_Old': 'pct_of_oi_m_money_short_old',
    'Pct_of_OI_M_Money_Spread_Old': 'pct_of_oi_m_money_spread_old',
    'Pct_of_OI_Other_Rept_Long_Old': 'pct_of_oi_other_rept_long_old',
    'Pct_of_OI_Other_Rept_Short_Old': 'pct_of_oi_other_rept_short_old',
    'Pct_of_OI_Other_Rept_Spread_Old': 'pct_of_oi_other_rept_spread_old',
    'Pct_of_OI_Tot_Rept_Long_Old': 'pct_of_oi_tot_rept_long_old',
    'Pct_of_OI_Tot_Rept_Short_Old': 'pct_of_oi_tot_rept_short_old',
    'Pct_of_OI_NonRept_Long_Old': 'pct_of_oi_nonrept_long_old',
    'Pct_of_OI_NonRept_Short_Old': 'pct_of_oi_nonrept_short_old',

    // Percentages - Other
    'Pct_of_Open_Interest_Other': 'pct_of_open_interest_other',
    'Pct_of_OI_Prod_Merc_Long_Other': 'pct_of_oi_prod_merc_long_other',
    'Pct_of_OI_Prod_Merc_Short_Other': 'pct_of_oi_prod_merc_short_other',
    'Pct_of_OI_Swap_Long_Other': 'pct_of_oi_swap_long_other',
    'Pct_of_OI_Swap_Short_Other': 'pct_of_oi_swap_short_other',
    'Pct_of_OI_Swap_Spread_Other': 'pct_of_oi_swap_spread_other',
    'Pct_of_OI_M_Money_Long_Other': 'pct_of_oi_m_money_long_other',
    'Pct_of_OI_M_Money_Short_Other': 'pct_of_oi_m_money_short_other',
    'Pct_of_OI_M_Money_Spread_Other': 'pct_of_oi_m_money_spread_other',
    'Pct_of_OI_Other_Rept_Long_Other': 'pct_of_oi_other_rept_long_other',
    'Pct_of_OI_Other_Rept_Short_Other': 'pct_of_oi_other_rept_short_other',
    'Pct_of_OI_Other_Rept_Spread_Othr': 'pct_of_oi_other_rept_spread_othr',
    'Pct_of_OI_Tot_Rept_Long_Other': 'pct_of_oi_tot_rept_long_other',
    'Pct_of_OI_Tot_Rept_Short_Other': 'pct_of_oi_tot_rept_short_other',
    'Pct_of_OI_NonRept_Long_Other': 'pct_of_oi_nonrept_long_other',
    'Pct_of_OI_NonRept_Short_Other': 'pct_of_oi_nonrept_short_other',

    // Traders - All
    'Traders_Tot_All': 'traders_tot_all',
    'Traders_Prod_Merc_Long_All': 'traders_prod_merc_long_all',
    'Traders_Prod_Merc_Short_All': 'traders_prod_merc_short_all',
    'Traders_Swap_Long_All': 'traders_swap_long_all',
    'Traders_Swap_Short_All': 'traders_swap_short_all',
    'Traders_Swap_Spread_All': 'traders_swap_spread_all',
    'Traders_M_Money_Long_All': 'traders_m_money_long_all',
    'Traders_M_Money_Short_All': 'traders_m_money_short_all',
    'Traders_M_Money_Spread_All': 'traders_m_money_spread_all',
    'Traders_Other_Rept_Long_All': 'traders_other_rept_long_all',
    'Traders_Other_Rept_Short_All': 'traders_other_rept_short_all',
    'Traders_Other_Rept_Spread_All': 'traders_other_rept_spread_all',
    'Traders_Tot_Rept_Long_All': 'traders_tot_rept_long_all',
    'Traders_Tot_Rept_Short_All': 'traders_tot_rept_short_all',

    // Traders - Old
    'Traders_Tot_Old': 'traders_tot_old',
    'Traders_Prod_Merc_Long_Old': 'traders_prod_merc_long_old',
    'Traders_Prod_Merc_Short_Old': 'traders_prod_merc_short_old',
    'Traders_Swap_Long_Old': 'traders_swap_long_old',
    'Traders_Swap_Short_Old': 'traders_swap_short_old',
    'Traders_Swap_Spread_Old': 'traders_swap_spread_old',
    'Traders_M_Money_Long_Old': 'traders_m_money_long_old',
    'Traders_M_Money_Short_Old': 'traders_m_money_short_old',
    'Traders_M_Money_Spread_Old': 'traders_m_money_spread_old',
    'Traders_Other_Rept_Long_Old': 'traders_other_rept_long_old',
    'Traders_Other_Rept_Short_Old': 'traders_other_rept_short_old',
    'Traders_Other_Rept_Spread_Old': 'traders_other_rept_spread_old',
    'Traders_Tot_Rept_Long_Old': 'traders_tot_rept_long_old',
    'Traders_Tot_Rept_Short_Old': 'traders_tot_rept_short_old',

    // Traders - Other
    'Traders_Tot_Other': 'traders_tot_other',
    'Traders_Prod_Merc_Long_Other': 'traders_prod_merc_long_other',
    'Traders_Prod_Merc_Short_Other': 'traders_prod_merc_short_other',
    'Traders_Swap_Long_Other': 'traders_swap_long_other',
    'Traders_Swap_Short_Other': 'traders_swap_short_other',
    'Traders_Swap_Spread_Other': 'traders_swap_spread_other',
    'Traders_M_Money_Long_Other': 'traders_m_money_long_other',
    'Traders_M_Money_Short_Other': 'traders_m_money_short_other',
    'Traders_M_Money_Spread_Other': 'traders_m_money_spread_other',
    'Traders_Other_Rept_Long_Other': 'traders_other_rept_long_other',
    'Traders_Other_Rept_Short_Other': 'traders_other_rept_short_other',
    'Traders_Other_Rept_Spread_Other': 'traders_other_rept_spread_other',
    'Traders_Tot_Rept_Long_Other': 'traders_tot_rept_long_other',
    'Traders_Tot_Rept_Short_Other': 'traders_tot_rept_short_other',

    // Concentration - All
    'Conc_Gross_LE_4_TDR_Long_All': 'conc_gross_le_4_tdr_long_all',
    'Conc_Gross_LE_4_TDR_Short_All': 'conc_gross_le_4_tdr_short_all',
    'Conc_Gross_LE_8_TDR_Long_All': 'conc_gross_le_8_tdr_long_all',
    'Conc_Gross_LE_8_TDR_Short_All': 'conc_gross_le_8_tdr_short_all',
    'Conc_Net_LE_4_TDR_Long_All': 'conc_net_le_4_tdr_long_all',
    'Conc_Net_LE_4_TDR_Short_All': 'conc_net_le_4_tdr_short_all',
    'Conc_Net_LE_8_TDR_Long_All': 'conc_net_le_8_tdr_long_all',
    'Conc_Net_LE_8_TDR_Short_All': 'conc_net_le_8_tdr_short_all',

    // Concentration - Old
    'Conc_Gross_LE_4_TDR_Long_Old': 'conc_gross_le_4_tdr_long_old',
    'Conc_Gross_LE_4_TDR_Short_Old': 'conc_gross_le_4_tdr_short_old',
    'Conc_Gross_LE_8_TDR_Long_Old': 'conc_gross_le_8_tdr_long_old',
    'Conc_Gross_LE_8_TDR_Short_Old': 'conc_gross_le_8_tdr_short_old',
    'Conc_Net_LE_4_TDR_Long_Old': 'conc_net_le_4_tdr_long_old',
    'Conc_Net_LE_4_TDR_Short_Old': 'conc_net_le_4_tdr_short_old',
    'Conc_Net_LE_8_TDR_Long_Old': 'conc_net_le_8_tdr_long_old',
    'Conc_Net_LE_8_TDR_Short_Old': 'conc_net_le_8_tdr_short_old',

    // Concentration - Other
    'Conc_Gross_LE_4_TDR_Long_Other': 'conc_gross_le_4_tdr_long_other',
    'Conc_Gross_LE_4_TDR_Short_Other': 'conc_gross_le_4_tdr_short_other',
    'Conc_Gross_LE_8_TDR_Long_Other': 'conc_gross_le_8_tdr_long_other',
    'Conc_Gross_LE_8_TDR_Short_Other': 'conc_gross_le_8_tdr_short_other',
    'Conc_Net_LE_4_TDR_Long_Other': 'conc_net_le_4_tdr_long_other',
    'Conc_Net_LE_4_TDR_Short_Other': 'conc_net_le_4_tdr_short_other',
    'Conc_Net_LE_8_TDR_Long_Other': 'conc_net_le_8_tdr_long_other',
    'Conc_Net_LE_8_TDR_Short_Other': 'conc_net_le_8_tdr_short_other',

    // Metadata
    'Contract_Units': 'contract_units',
    'CFTC_SubGroup_Code': 'cftc_subgroup_code',
    'FutOnly_or_Combined': 'futonly_or_combined'
};

module.exports = { COMPLETE_COLUMN_MAPPING };
